class com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER extends com.rockstargames.gtav.web.vehicleSites.VehicleWebsite
{
   static var BRAND_NONE = "";
   static var BRAND_BF = "BF";
   static var BRAND_BRUTE = "BRUTE";
   static var BRAND_COIL = "COIL";
   static var BRAND_IMPONTE = "IMPONTE";
   static var BRAND_JOBUILT = "JOBUILT";
   static var BRAND_KARIN = "KARIN";
   static var BRAND_MTL = "MTL";
   static var BRAND_NAGASAKI = "NAGASAKI";
   static var TXD_DEFAULT = "CANDC_DEFAULT";
   static var TXD_APARTMENTS = "CANDC_APARTMENTS";
   static var TXD_EXECUTIVE1 = "CANDC_EXECUTIVE1";
   static var TXD_IMPORT_EXPORT = "CANDC_IMPORTEXPORT";
   static var TXD_GUNRUNNING = "CANDC_GUNRUNNING";
   static var TXD_SMUGGLER = "CANDC_SMUGGLER";
   static var TXD_XMAS2017 = "CANDC_XMAS2017";
   static var TXD_ASSAULT = "CANDC_ASSAULT";
   static var TXD_BATTLE = "CANDC_BATTLE";
   static var TXD_CASINOHEIST = "CANDC_CASINOHEIST";
   static var TXD_HEIST4 = "CANDC_HEIST4";
   static var TXD_XMAS2022 = "CANDC_XMAS2022";
   static var TXD_2023_01 = "CANDC_2023_01";
   static var TXD_2023_02 = "CANDC_2023_2";
   static var TXD_2024_01 = "CANDC_DLC_2024_1";
   static var TXD_2024_02 = "CANDC_DLC_2024_2";
   static var TXD_2025_1 = "CANDC_DLC_2025_1";
   static var DLC_HIPSTER = "WEB_HIPSTERPACK";
   static var DLC_INDEPENDENCE = "WEB_INDEPENDENCEPACK";
   static var DLC_HEIST = "WEB_HEISTPACK";
   static var DLC_APARTMENTS = "WEB_APARTMENTSPACK";
   static var DLC_EXECUTIVE1 = "WEB_EXECUTIVE1PACK";
   static var DLC_IMPORT_EXPORT = "WEB_IMPORTEXPORTPACK";
   static var DLC_GUNRUNNING = "WEB_GUNRUNNINGPACK";
   static var DLC_SMUGGLER = "WEB_SMUGGLERPACK";
   static var DLC_XMAS2017 = "WEB_XMAS2017PACK";
   static var DLC_ASSAULT = "WEB_ASSAULTPACK";
   static var DLC_BATTLE = "WEB_BATTLEPACK";
   static var DLC_CASINOHEIST = "WEB_CASINOHEISTPACK";
   static var DLC_HEIST4 = "WEB_HEIST4PACK";
   static var DLC_XMAS2022 = "WEB_XMAS2022";
   static var DLC_2023_01 = "WEB_2023_01";
   static var DLC_2023_02 = "WEB_2023_02";
   static var DLC_2024_01 = "WEB_2024_01";
   static var DLC_2024_02 = "WEB_2024_02";
   static var DLC_2025_1 = "WEB_2025_01";
   static var TXD_GEN9 = "CANDC_GEN9";
   static var DLC_GEN9 = "WEB_GEN9";
   var vehicles = {RHINO:{id:3,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:1,colourways:false},BARRACKS:{id:5,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:10,colourways:false},CARGOBOB:{id:7,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_EXECUTIVE1,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:10,colourways:false},BUZZARD:{id:8,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false},CRUSADER:{id:10,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false},AIRBUS:{id:17,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:16,colourways:false},JOURNEY:{id:18,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:6,colourways:false},COACH:{id:20,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:10,colourways:false},BUS:{id:21,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .TXD_DEFAULT,seats:16,colourways:false},MULE:{id:24,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:6,colourways:false},RENTBUS:{id:27,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:10,colourways:false},DUMP:{id:28,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:1,colourways:false},DUBSTA3:{id:29,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HIPSTER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:6,colourways:false},MONSTER:{id:30,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_INDEPENDENCE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:2,colourways:false},BOXVILLE4:{id:31,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false,buyItNow:true},VALKYRIE:{id:32,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false,buyItNow:true},HYDRA:{id:33,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:1,colourways:false,buyItNow:true},INSURGENT:{id:34,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:9,colourways:false,buyItNow:true},INSURGENT2:{id:35,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:6,colourways:false,buyItNow:true},MULE3:{id:36,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames
   .gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:6,colourways:false,buyItNow:true},SAVAGE:{id:37,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false,buyItNow:true},TECHNICAL:{id:38,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:3,colourways:false,buyItNow:true},MESA3:{id:39,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:4,colourways:false},PBUS:{id:40,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:11,colourways:false,buyItNow:true},MARSHALL:{id:41,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:2,colourways:false,flags:true,desc:"CANDC_DLCMARSHALL"},DUKES2:{id:42,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_DEFAULT,seats:2,colourways:false,desc:"CANDC_DLCDUKES2"},LIMO2:{id:43,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .BRAND_NONE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_APARTMENTS,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_APARTMENTS,seats:5,colourways:false},CARGOBOB2:{id:44,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_EXECUTIVE1,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_EXECUTIVE1,seats:10,colourways:false},BRICKADE:{id:45,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_EXECUTIVE1,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_EXECUTIVE1,seats:6,colourways:false},DUNE5:{id:46,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:2,colourways:false,securoserv:true},PHANTOM2:{id:47,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:5,colourways:false,securoserv:true},TECHNICAL2:{id:48,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:3,colourways:false,securoserv:true},BLAZER5:{id:49,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:1,colourways:false,securoserv:true},BOXVILLE5:{id:50,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:5,colourways:false,securoserv:true},WASTLNDR:{id:51,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:6,colourways:false,securoserv:true},RUINER2:{id:52,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:2,colourways:false,securoserv:true},VOLTIC2:{id:53,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_IMPORT_EXPORT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_IMPORT_EXPORT,seats:2,colourways:false,securoserv:true},BALLISTIC_EQUIP:{id:63,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:1,colourways:false,unlockable:true},APC:{id:64,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:4,colourways:false,buyItNow:true},DUNE3:{id:65,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:2,colourways:false,buyItNow:true},HALFTRACK:{id:66,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:3,colourways:false,buyItNow:true},OPPRESSOR:{id:67,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:1,colourways:false,buyItNow:true},TAMPA3:{id:68,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:2,colourways:false,buyItNow:true},TRSMALL2:{id:69,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:1,colourways:false,buyItNow:true},ARDENT:{id:70,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames
   .gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:2,colourways:true},NIGHTSHARK:{id:71,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GUNRUNNING,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_GUNRUNNING,seats:4,colourways:true},LAZER:{id:72,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:1,colourways:false},MOGUL:{id:73,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .TXD_SMUGGLER,seats:3,colourways:false,buyItNow:true},ROGUE:{id:74,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:2,colourways:false,buyItNow:true},STARLING:{id:75,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:1,colourways:false,buyItNow:true},TULA:{id:76,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:5,colourways:false,buyItNow:true},PYRO:{id:77,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:2,colourways:false,buyItNow:true},MOLOTOK:{id:78,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:1,colourways:false,buyItNow:true},NOKOTA:{id:79,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:1,colourways:false,buyItNow:true},BOMBUSHKA:{id:80,brand:com.rockstargames.gtav
   .web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:6,colourways:false,buyItNow:true},HUNTER:{id:81,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:2,colourways:false,buyItNow:true},VIGILANTE:{id:82,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_SMUGGLER,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_SMUGGLER,seats:2,colourways:false},DELUXO:{id:91,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:2,colourways:false,buyItNow:true},STROMBERG:{id:92,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:2,colourways:false,buyItNow:true},RIOT2:{id:93,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:6,colourways:false,buyItNow:true},CHERNOBOG:{id:94,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:2,colourways:false,buyItNow:true},KHANJALI:{id:95,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:4,colourways:false,buyItNow:true},AKULA:{id:96,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:4,colourways:false,buyItNow:true},THRUSTER:{id:97,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav
   .web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:1,colourways:false,buyItNow:true},BARRAGE:{id:98,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:4,colourways:false,buyItNow:true},VOLATOL:{id:99,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2017,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2017,seats:4,colourways:false,buyItNow:true},CARACARA:{id:100,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_ASSAULT,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_ASSAULT,seats:5,colourways:false},MULE4:{id:111,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:4,colourways:false,buyItNow:true},POUNDER2:{id:112,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:8,colourways:false,buyItNow:true},MENACER:{id:113,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web
   .WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:5,colourways:false},SCRAMJET:{id:114,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:2,colourways:false},STRIKEFORCE:{id:115,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:1,colourways:false},OPPRESSOR2:{id:116,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_BATTLE,seats:1,colourways:false,buyItNow:true},FIRETRUK:{id:117,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:8,colourways:false,buyItNow:true},BURRITO2:{id:118,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:4,colourways:false,buyItNow:true},BOXVILLE:{id:119,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:6,colourways:false,buyItNow:true},STOCKADE:{id:120,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:4,colourways:false,buyItNow:true},LGUARD:{id:121,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:4,colourways:false,buyItNow:false},BLAZER2:{id:122,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:1,colourways:false,buyItNow:false},ZHABA:{id:123,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:4,colourways:false,buyItNow:true},MINITANK:{id:124,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:1,colourways:false,buyItNow:true},JB7002:{id:125,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_CASINOHEIST,seats:2,colourways:false},ALKONOST:{id:148,brand:com.rockstargames
   .gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:2,colourways:false,buyItNow:true},ANNIHLATOR2:{id:149,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:6,colourways:false,buyItNow:true},AVISA:{id:150,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:4,colourways:false},DINGHY5:{id:151,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:5,colourways:false},MANCHEZ2:{id:152,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:1,colourways:false,buyItNow:true},PATROLBOAT:{id:153,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:4,colourways:false,buyItNow:true},SPARROW3:{id:154,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav
   .web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:2,colourways:false},SQUADDIE:{id:155,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:4,colourways:false,buyItNow:true},TOREADOR:{id:156,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:4,colourways:false},VERUS:{id:157,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:2,colourways:false},VETIR:{id:158,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:10,colourways:false,buyItNow:true},WINKY:{id:159,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_HEIST4,seats:3,colourways:false,buyItNow:true},IGNUS2:{id:160,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_GEN9,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .TXD_GEN9,seats:2,colourways:false,buyItNow:false,isGen9:true},BRICKADE2:{id:161,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2022,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2022,seats:6,colourways:false},TAXI:{id:162,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_XMAS2022,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_XMAS2022,seats:4,colourways:false,buyItNow:true},STREAMER216:{id:164,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_01,seats:4,colourways:false,buyItNow:false},RAIJU:{id:165,brand:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_01,seats:1,colourways:false,buyItNow:true},CONADA2:{id:166,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_01,seats:2,colourways:false,buyItNow:false},POLGAUNTLET:{id:167,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:2,colourways:false,buyItNow:true},PRANGER:{id:168,brand:com.rockstargames.gtav
   .web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:8,colourways:false,buyItNow:true,isGen9:false},POLICE4:{id:169,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:4,colourways:false,buyItNow:true},POLICE5:{id:170,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:4,colourways:false,buyItNow:true},RIOT:{id:171,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:8,colourways:false,buyItNow:true},BENSON2:{id:172,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:2,colourways:false,buyItNow:true},BOXVILLE6:{id:173,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2023_02,seats:6,colourways:false,buyItNow:true},POLIMPALER5:{id:174,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_01,seats:4,colourways:false,buyItNow:true},POLIMPALER6:{id:175,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_01,seats:4,colourways:false,buyItNow:true},POLGREENW:{id:176,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_01,seats:4,colourways:false,buyItNow:true},POLDORADO:{id:177,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames
   .gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_01,seats:4,colourways:false,buyItNow:true},POLDOM10:{id:178,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_01,seats:2,colourways:false,buyItNow:true},POLCARACAR:{id:179,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:4,colourways:false,buyItNow:true},POLTERMINU:{id:180,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER
   .DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:4,colourways:false,buyItNow:true},POLCOQUTT4:{id:181,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:2,colourways:false,buyItNow:true},POLFCTION2:{id:182,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:2,colourways:false,buyItNow:true},TACO:{id:183,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com
   .rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:1,colourways:false,buyItNow:true},PREDATOR:{id:184,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:4,colourways:false,buyItNow:true},CARGOBOB5:{id:185,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:16,colourways:false,buyItNow:true},TITAN2:{id:186,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2024_02,txd:com.rockstargames.gtav
   .web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2024_02,seats:16,colourways:false,buyItNow:true},STOCKADE4:{id:187,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2025_1,seats:4,colourways:false,buyItNow:true},POLICEB2:{id:188,brand:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER.TXD_2025_1,seats:1,colourways:false,buyItNow:true}};
   function WWW_WARSTOCK_D_CACHE_D_AND_D_CARRY_COM_WRAPPER()
   {
      super();
   }
}
