class com.rockstargames.gtav.cellphone.IconLabels
{
   static var _instance;
   static var CAMERA = new Array(1,"CAMERA");
   static var TEXT_MESSAGE = new Array(2,"TEXT_MESSAGE");
   static var CALENDAR = new Array(3,"CALENDAR");
   static var EMAIL = new Array(4,"EMAIL");
   static var CALL = new Array(5,"CALL");
   static var EYEFIND = new Array(6,"EYEFIND");
   static var MAP = new Array(7,"MAP");
   static var APPS = new Array(8,"APPS");
   static var MEDIA = new Array(9,"MEDIA");
   static var ATTACHMENT = new Array(10,"ATTACHMENT");
   static var NEW_CONTACT = new Array(11,"NEW_CONTACT");
   static var SIDE_TASKS = new Array(12,"SIDE_TASKS");
   static var BAWSAQ = new Array(13,"BAWSAQ");
   static var MULTIPLAYER = new Array(14,"MULTIPLAYER");
   static var MUSIC = new Array(15,"MUSIC");
   static var GPS = new Array(16,"GPS");
   static var SPARE = new Array(17,"SPARE");
   static var RINGTONE = new Array(18,"RINGTONE");
   static var TEXT_TONE = new Array(19,"TEXT_TONE");
   static var VIBRATE_ON = new Array(20,"VIBRATE_ON");
   static var VIBRATE_OFF = new Array(21,"VIBRATE_OFF");
   static var VOLUME = new Array(22,"VOLUME");
   static var SETTINGS_1 = new Array(23,"SETTINGS_1");
   static var SETTINGS_2 = new Array(24,"SETTINGS_2");
   static var PROFILE = new Array(25,"PROFILE");
   static var SLEEP_MODE = new Array(26,"SLEEP_MODE");
   static var MISSED_CALL = new Array(27,"MISSED_CALL");
   static var UNREAD_EMAIL = new Array(28,"UNREAD_EMAIL");
   static var READ_EMAIL = new Array(29,"READ_EMAIL");
   static var REPLY_EMAIL = new Array(30,"REPLY_EMAIL");
   static var REPLAYMISSION = new Array(31,"REPLAYMISSION");
   static var SHITSKIP = new Array(32,"SHITSKIP");
   static var UNREAD_SMS = new Array(33,"UNREAD_SMS");
   static var READ_SMS = new Array(34,"READ_SMS");
   static var PLAYER_LIST = new Array(35,"PLAYER_LIST");
   static var COP_BACKUP = new Array(36,"COP_BACKUP");
   static var GANG_TAXI = new Array(37,"GANG_TAXI");
   static var REPEAT_PLAY = new Array(38,"REPEAT_PLAY");
   static var CHECKLIST = new Array(39,"CHECKLIST");
   static var SNIPER = new Array(40,"SNIPER");
   static var ZIT_IT = new Array(41,"ZIT_IT");
   static var TRACKIFY = new Array(42,"TRACKIFY");
   static var SAVE = new Array(43,"SAVE");
   static var ADD_TAG = new Array(44,"ADD_TAG");
   static var REMOVE_TAG = new Array(45,"REMOVE_TAG");
   static var LOCATION = new Array(46,"LOCATION");
   static var PARTY = new Array(47,"PARTY");
   static var TICKED = new Array(48,"TICKED");
   static var BROADCAST = new Array(49,"BROADCAST");
   static var GAMEPAD = new Array(50,"GAMEPAD");
   static var SILENT = new Array(51,"SILENT");
   static var INVITES_PENDING = new Array(52,"INVITES_PENDING");
   static var ON_CALL = new Array(53,"ON_CALL");
   static var H_LOCK = new Array(54,"H_LOCK");
   static var PUSH_TO_TALK = new Array(55,"PUSH_TO_TALK");
   static var BENNYS = new Array(56,"BENNYS");
   static var GANG = new Array(57,"GANG");
   static var TRACKER = new Array(58,"TRACKER");
   static var SIGHT_SEER = new Array(59,"SIGHT_SEER");
   static var BEACON = new Array(60,"BEACON");
   static var VINEWOOD = new Array(61,"VINEWOOD");
   static var DARNELL = new Array(62,"DARNELL");
   var HASHTABLE = new Object();
   var PREFIX = "il";
   function IconLabels()
   {
      this.HASHTABLE = new Object();
      this.HASHTABLE[this.PREFIX + "0"] = null;
      this.HASHTABLE[this.PREFIX + "1"] = com.rockstargames.gtav.cellphone.IconLabels.CAMERA;
      this.HASHTABLE[this.PREFIX + "2"] = com.rockstargames.gtav.cellphone.IconLabels.TEXT_MESSAGE;
      this.HASHTABLE[this.PREFIX + "3"] = com.rockstargames.gtav.cellphone.IconLabels.CALENDAR;
      this.HASHTABLE[this.PREFIX + "4"] = com.rockstargames.gtav.cellphone.IconLabels.EMAIL;
      this.HASHTABLE[this.PREFIX + "5"] = com.rockstargames.gtav.cellphone.IconLabels.CALL;
      this.HASHTABLE[this.PREFIX + "6"] = com.rockstargames.gtav.cellphone.IconLabels.EYEFIND;
      this.HASHTABLE[this.PREFIX + "7"] = com.rockstargames.gtav.cellphone.IconLabels.MAP;
      this.HASHTABLE[this.PREFIX + "8"] = com.rockstargames.gtav.cellphone.IconLabels.APPS;
      this.HASHTABLE[this.PREFIX + "9"] = com.rockstargames.gtav.cellphone.IconLabels.MEDIA;
      this.HASHTABLE[this.PREFIX + "10"] = com.rockstargames.gtav.cellphone.IconLabels.ATTACHMENT;
      this.HASHTABLE[this.PREFIX + "11"] = com.rockstargames.gtav.cellphone.IconLabels.NEW_CONTACT;
      this.HASHTABLE[this.PREFIX + "12"] = com.rockstargames.gtav.cellphone.IconLabels.SIDE_TASKS;
      this.HASHTABLE[this.PREFIX + "13"] = com.rockstargames.gtav.cellphone.IconLabels.BAWSAQ;
      this.HASHTABLE[this.PREFIX + "14"] = com.rockstargames.gtav.cellphone.IconLabels.MULTIPLAYER;
      this.HASHTABLE[this.PREFIX + "15"] = com.rockstargames.gtav.cellphone.IconLabels.MUSIC;
      this.HASHTABLE[this.PREFIX + "16"] = com.rockstargames.gtav.cellphone.IconLabels.GPS;
      this.HASHTABLE[this.PREFIX + "17"] = com.rockstargames.gtav.cellphone.IconLabels.SPARE;
      this.HASHTABLE[this.PREFIX + "18"] = com.rockstargames.gtav.cellphone.IconLabels.RINGTONE;
      this.HASHTABLE[this.PREFIX + "19"] = com.rockstargames.gtav.cellphone.IconLabels.TEXT_TONE;
      this.HASHTABLE[this.PREFIX + "20"] = com.rockstargames.gtav.cellphone.IconLabels.VIBRATE_ON;
      this.HASHTABLE[this.PREFIX + "21"] = com.rockstargames.gtav.cellphone.IconLabels.VIBRATE_OFF;
      this.HASHTABLE[this.PREFIX + "22"] = com.rockstargames.gtav.cellphone.IconLabels.VOLUME;
      this.HASHTABLE[this.PREFIX + "23"] = com.rockstargames.gtav.cellphone.IconLabels.SETTINGS_1;
      this.HASHTABLE[this.PREFIX + "24"] = com.rockstargames.gtav.cellphone.IconLabels.SETTINGS_2;
      this.HASHTABLE[this.PREFIX + "25"] = com.rockstargames.gtav.cellphone.IconLabels.PROFILE;
      this.HASHTABLE[this.PREFIX + "26"] = com.rockstargames.gtav.cellphone.IconLabels.SLEEP_MODE;
      this.HASHTABLE[this.PREFIX + "27"] = com.rockstargames.gtav.cellphone.IconLabels.MISSED_CALL;
      this.HASHTABLE[this.PREFIX + "28"] = com.rockstargames.gtav.cellphone.IconLabels.UNREAD_EMAIL;
      this.HASHTABLE[this.PREFIX + "29"] = com.rockstargames.gtav.cellphone.IconLabels.READ_EMAIL;
      this.HASHTABLE[this.PREFIX + "30"] = com.rockstargames.gtav.cellphone.IconLabels.REPLY_EMAIL;
      this.HASHTABLE[this.PREFIX + "31"] = com.rockstargames.gtav.cellphone.IconLabels.REPLAYMISSION;
      this.HASHTABLE[this.PREFIX + "32"] = com.rockstargames.gtav.cellphone.IconLabels.SHITSKIP;
      this.HASHTABLE[this.PREFIX + "33"] = com.rockstargames.gtav.cellphone.IconLabels.UNREAD_SMS;
      this.HASHTABLE[this.PREFIX + "34"] = com.rockstargames.gtav.cellphone.IconLabels.READ_SMS;
      this.HASHTABLE[this.PREFIX + "35"] = com.rockstargames.gtav.cellphone.IconLabels.PLAYER_LIST;
      this.HASHTABLE[this.PREFIX + "36"] = com.rockstargames.gtav.cellphone.IconLabels.COP_BACKUP;
      this.HASHTABLE[this.PREFIX + "37"] = com.rockstargames.gtav.cellphone.IconLabels.GANG_TAXI;
      this.HASHTABLE[this.PREFIX + "38"] = com.rockstargames.gtav.cellphone.IconLabels.REPEAT_PLAY;
      this.HASHTABLE[this.PREFIX + "39"] = com.rockstargames.gtav.cellphone.IconLabels.CHECKLIST;
      this.HASHTABLE[this.PREFIX + "40"] = com.rockstargames.gtav.cellphone.IconLabels.SNIPER;
      this.HASHTABLE[this.PREFIX + "41"] = com.rockstargames.gtav.cellphone.IconLabels.ZIT_IT;
      this.HASHTABLE[this.PREFIX + "42"] = com.rockstargames.gtav.cellphone.IconLabels.TRACKIFY;
      this.HASHTABLE[this.PREFIX + "43"] = com.rockstargames.gtav.cellphone.IconLabels.SAVE;
      this.HASHTABLE[this.PREFIX + "44"] = com.rockstargames.gtav.cellphone.IconLabels.ADD_TAG;
      this.HASHTABLE[this.PREFIX + "45"] = com.rockstargames.gtav.cellphone.IconLabels.REMOVE_TAG;
      this.HASHTABLE[this.PREFIX + "46"] = com.rockstargames.gtav.cellphone.IconLabels.LOCATION;
      this.HASHTABLE[this.PREFIX + "47"] = com.rockstargames.gtav.cellphone.IconLabels.PARTY;
      this.HASHTABLE[this.PREFIX + "48"] = com.rockstargames.gtav.cellphone.IconLabels.TICKED;
      this.HASHTABLE[this.PREFIX + "49"] = com.rockstargames.gtav.cellphone.IconLabels.BROADCAST;
      this.HASHTABLE[this.PREFIX + "50"] = com.rockstargames.gtav.cellphone.IconLabels.GAMEPAD;
      this.HASHTABLE[this.PREFIX + "51"] = com.rockstargames.gtav.cellphone.IconLabels.SILENT;
      this.HASHTABLE[this.PREFIX + "52"] = com.rockstargames.gtav.cellphone.IconLabels.INVITES_PENDING;
      this.HASHTABLE[this.PREFIX + "53"] = com.rockstargames.gtav.cellphone.IconLabels.ON_CALL;
      this.HASHTABLE[this.PREFIX + "54"] = com.rockstargames.gtav.cellphone.IconLabels.H_LOCK;
      this.HASHTABLE[this.PREFIX + "55"] = com.rockstargames.gtav.cellphone.IconLabels.PUSH_TO_TALK;
      this.HASHTABLE[this.PREFIX + "56"] = com.rockstargames.gtav.cellphone.IconLabels.BENNYS;
      this.HASHTABLE[this.PREFIX + "57"] = com.rockstargames.gtav.cellphone.IconLabels.GANG;
      this.HASHTABLE[this.PREFIX + "58"] = com.rockstargames.gtav.cellphone.IconLabels.TRACKER;
      this.HASHTABLE[this.PREFIX + "59"] = com.rockstargames.gtav.cellphone.IconLabels.SIGHT_SEER;
      this.HASHTABLE[this.PREFIX + "60"] = com.rockstargames.gtav.cellphone.IconLabels.BEACON;
      this.HASHTABLE[this.PREFIX + "61"] = com.rockstargames.gtav.cellphone.IconLabels.VINEWOOD;
      this.HASHTABLE[this.PREFIX + "62"] = com.rockstargames.gtav.cellphone.IconLabels.DARNELL;
   }
   static function lookUp(i)
   {
      if(com.rockstargames.gtav.cellphone.IconLabels._instance == undefined)
      {
         com.rockstargames.gtav.cellphone.IconLabels._instance = new com.rockstargames.gtav.cellphone.IconLabels();
      }
      return com.rockstargames.gtav.cellphone.IconLabels._instance.HASHTABLE[com.rockstargames.gtav.cellphone.IconLabels._instance.PREFIX + i];
   }
}
