class com.rockstargames.ui.utils.HudColour
{
   var r;
   var g;
   var b;
   var a;
   static var HUD_COLOUR_PURE_WHITE = 0;
   static var HUD_COLOUR_WHITE = 1;
   static var HUD_COLOUR_BLACK = 2;
   static var HUD_COLOUR_GREY = 3;
   static var HUD_COLOUR_GREYLIGHT = 4;
   static var HUD_COLOUR_GREYDARK = 5;
   static var HUD_COLOUR_RED = 6;
   static var HUD_COLOUR_REDLIGHT = 7;
   static var HUD_COLOUR_REDDARK = 8;
   static var HUD_COLOUR_BLUE = 9;
   static var HUD_COLOUR_BLUELIGHT = 10;
   static var HUD_COLOUR_BLUEDARK = 11;
   static var HUD_COLOUR_YELLOW = 12;
   static var HUD_COLOUR_YELLOWLIGHT = 13;
   static var HUD_COLOUR_YELLOWDARK = 14;
   static var HUD_COLOUR_ORANGE = 15;
   static var HUD_COLOUR_ORANGELIGHT = 16;
   static var HUD_COLOUR_ORANGEDARK = 17;
   static var HUD_COLOUR_GREEN = 18;
   static var HUD_COLOUR_GREENLIGHT = 19;
   static var HUD_COLOUR_GREENDARK = 20;
   static var HUD_COLOUR_PURPLE = 21;
   static var HUD_COLOUR_PURPLELIGHT = 22;
   static var HUD_COLOUR_PURPLEDARK = 23;
   static var HUD_COLOUR_PINK = 24;
   static var HUD_COLOUR_RADAR_HEALTH = 25;
   static var HUD_COLOUR_RADAR_ARMOUR = 26;
   static var HUD_COLOUR_RADAR_DAMAGE = 27;
   static var HUD_COLOUR_NET_PLAYER1 = 28;
   static var HUD_COLOUR_NET_PLAYER2 = 29;
   static var HUD_COLOUR_NET_PLAYER3 = 30;
   static var HUD_COLOUR_NET_PLAYER4 = 31;
   static var HUD_COLOUR_NET_PLAYER5 = 32;
   static var HUD_COLOUR_NET_PLAYER6 = 33;
   static var HUD_COLOUR_NET_PLAYER7 = 34;
   static var HUD_COLOUR_NET_PLAYER8 = 35;
   static var HUD_COLOUR_NET_PLAYER9 = 36;
   static var HUD_COLOUR_NET_PLAYER10 = 37;
   static var HUD_COLOUR_NET_PLAYER11 = 38;
   static var HUD_COLOUR_NET_PLAYER12 = 39;
   static var HUD_COLOUR_NET_PLAYER13 = 40;
   static var HUD_COLOUR_NET_PLAYER14 = 41;
   static var HUD_COLOUR_NET_PLAYER15 = 42;
   static var HUD_COLOUR_NET_PLAYER16 = 43;
   static var HUD_COLOUR_NET_PLAYER17 = 44;
   static var HUD_COLOUR_NET_PLAYER18 = 45;
   static var HUD_COLOUR_NET_PLAYER19 = 46;
   static var HUD_COLOUR_NET_PLAYER20 = 47;
   static var HUD_COLOUR_NET_PLAYER21 = 48;
   static var HUD_COLOUR_NET_PLAYER22 = 49;
   static var HUD_COLOUR_NET_PLAYER23 = 50;
   static var HUD_COLOUR_NET_PLAYER24 = 51;
   static var HUD_COLOUR_NET_PLAYER25 = 52;
   static var HUD_COLOUR_NET_PLAYER26 = 53;
   static var HUD_COLOUR_NET_PLAYER27 = 54;
   static var HUD_COLOUR_NET_PLAYER28 = 55;
   static var HUD_COLOUR_NET_PLAYER29 = 56;
   static var HUD_COLOUR_NET_PLAYER30 = 57;
   static var HUD_COLOUR_NET_PLAYER31 = 58;
   static var HUD_COLOUR_NET_PLAYER32 = 59;
   static var HUD_COLOUR_SIMPLEBLIP_DEFAULT = 60;
   static var HUD_COLOUR_MENU_BLUE = 61;
   static var HUD_COLOUR_MENU_GREY_LIGHT = 62;
   static var HUD_COLOUR_MENU_BLUE_EXTRA_DARK = 63;
   static var HUD_COLOUR_MENU_YELLOW = 64;
   static var HUD_COLOUR_MENU_YELLOW_DARK = 65;
   static var HUD_COLOUR_MENU_GREEN = 66;
   static var HUD_COLOUR_MENU_GREY = 67;
   static var HUD_COLOUR_MENU_GREY_DARK = 68;
   static var HUD_COLOUR_MENU_HIGHLIGHT = 69;
   static var HUD_COLOUR_MENU_STANDARD = 70;
   static var HUD_COLOUR_MENU_DIMMED = 71;
   static var HUD_COLOUR_MENU_EXTRA_DIMMED = 72;
   static var HUD_COLOUR_BRIEF_TITLE = 73;
   static var HUD_COLOUR_MID_GREY_MP = 74;
   function HudColour()
   {
      this.r = 255;
      this.g = 255;
      this.b = 255;
      this.a = 100;
   }
}
