class com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER extends com.rockstargames.gtav.web.vehicleSites.VehicleWebsite
{
   var BRAND_ALBANY = "ALBANY";
   var BRAND_ANNIS = "ANNIS";
   var BRAND_BENEFAC = "BENEFAC";
   var BRAND_BENEFACTOR = "BENEFACTOR";
   var BRAND_BF = "BF";
   var BRAND_BOLLOKAN = "BOLLOKAN";
   var BRAND_BRAVADO = "BRAVADO";
   var BRAND_CANIS = "CANIS";
   var BRAND_CHARIOT = "CHARIOT";
   var BRAND_CHEVAL = "CHEVAL";
   var BRAND_DECLASSE = "DECLASSE";
   var BRAND_DEWBAUCH = "DEWBAUCH";
   var BRAND_DINKA = "DINKA";
   var BRAND_DUNDREAR = "DUNDREAR";
   var BRAND_DUNDREARY = "DUNDREARY";
   var BRAND_ENUS = "ENUS";
   var BRAND_EMPEROR = "EMPEROR";
   var BRAND_FATHOM = "FATHOM";
   var BRAND_GALLIVAN = "GALLIVAN";
   var BRAND_GROTTI = "GROTTI";
   var BRAND_IMPONTE = "IMPONTE";
   var BRAND_KARIN = "KARIN";
   var BRAND_LAMPADA = "LAMPADA";
   var BRAND_LCC = "LCC";
   var BRAND_MAIBATSU = "MAIBATSU";
   var BRAND_MAMMOTH = "MAMMOTH";
   var BRAND_MAXWELL = "MAXWELL";
   var BRAND_MTL = "MTL";
   var BRAND_NAGASAKI = "NAGASAKI";
   var BRAND_NONE = "";
   var BRAND_OBEY = "OBEY";
   var BRAND_OCELOT = "OCELOT";
   var BRAND_PEGASSI = "PEGASSI";
   var BRAND_PFISTER = "PFISTER";
   var BRAND_PRINCIPL = "PRINCIPL";
   var BRAND_PRINCIPLE = "PRINCIPLE";
   var BRAND_RUNE = "RUNE";
   var BRAND_SCHYSTER = "SCHYSTER";
   var BRAND_SHITZU = "SHITZU";
   var BRAND_UBERMACH = "UBERMACH";
   var BRAND_UBERMACHT = "UBERMACHT";
   var BRAND_VAPID = "VAPID";
   var BRAND_VULCAR = "VULCAR";
   var BRAND_WEENY = "WEENY";
   var BRAND_WESTERN = "WESTERN";
   var BRAND_WILLARD = "WILLARD";
   var BRAND_ZIRCONIU = "ZIRCONIU";
   var TXD_DEFAULT = "SSSA_DEFAULT";
   var TXD_BUSINESS = "SSSA_DLC_BUSINESS";
   var TXD_BUSINESS2 = "SSSA_DLC_BUSINESS2";
   var TXD_CHRISTMAS_2 = "SSSA_DLC_CHRISTMAS_2";
   var TXD_HEIST = "SSSA_DLC_HEIST";
   var TXD_HIPSTER = "SSSA_DLC_HIPSTER";
   var TXD_INDEPENDENCE = "SSSA_DLC_INDEPENDENCE";
   var TXD_LTS_CREATOR = "SSSA_DLC_LTS_CREATOR";
   var TXD_VALENTINES = "SSSA_DLC_VALENTINES";
   var TXD_MP_TO_SP = "SSSA_DLC_MP_TO_SP";
   var TXD_HALLOWEEN = "SSSA_DLC_HALLOWEEN";
   var TXD_APARTMENTS = "SSSA_DLC_APARTMENTS";
   var TXD_CHRISTMAS_3 = "SSSA_DLC_CHRISTMAS_3";
   var TXD_EXECUTIVE_1 = "SSSA_DLC_EXECUTIVE_1";
   var TXD_STUNT = "SSSA_DLC_STUNT";
   var TXD_BIKER = "SSSA_DLC_BIKER";
   var TXD_SMUGGLER = "SSSA_DLC_SMUGGLER";
   var TXD_XMAS_2017 = "SSSA_DLC_XMAS2017";
   var TXD_ASSAULT = "SSSA_DLC_ASSAULT";
   var TXD_BATTLE = "SSSA_DLC_BATTLE";
   var TXD_ARENA = "SSSA_DLC_ARENA";
   var TXD_VINEWOOD = "SSSA_DLC_VINEWOOD";
   var TXD_CASINOHEIST = "SSSA_DLC_CASINOHEIST";
   var TXD_SUMMER2020 = "SSSA_DLC_SUMMER2020";
   var TXD_HEIST4 = "SSSA_DLC_HEIST4";
   var TXD_TUNER = "SSSA_DLC_TUNER";
   var TXD_SECURITY = "SSSA_DLC_SECURITY";
   var TXD_SUM2 = "SSSA_DLC_SUM2";
   var TXD_XMAS_2022 = "SSSA_DLC_XMAS2022";
   var TXD_2023_01 = "SSSA_DLC_2023_01";
   var TXD_2023_02 = "SSSA_DLC_2023_2";
   var TXD_2024_01 = "SSSA_DLC_2024_1";
   var TXD_2024_02 = "SSSA_DLC_2024_2";
   var TXD_2025_1 = "SSSA_DLC_2025_1";
   var DLC_BEACH_BUM = "SSS_BEACHBUM";
   var DLC_VALENTINES = "WEB_VALENTINESPACK";
   var DLC_BUSINESS = "WEB_BUSINESSPACK";
   var DLC_BUSINESS_2 = "WEB_BUSINESSPACK2";
   var DLC_HIPSTER = "WEB_HIPSTERPACK";
   var DLC_INDEPENDENCE = "WEB_INDEPENDENCEPACK";
   var DLC_LTS_CREATOR = "WEB_LTSCREATORPACK";
   var DLC_CHRISTMAS_2 = "WEB_XMAS2";
   var DLC_HEIST = "WEB_HEISTPACK";
   var DLC_HALLOWEEN = "WEB_HALLOWEENPACK";
   var DLC_APARTMENTS = "WEB_APARTMENTSPACK";
   var DLC_CHRISTMAS_3 = "WEB_CHRISTMAS_3";
   var DLC_EXECUTIVE_1 = "WEB_EXECUTIVE1PACK";
   var DLC_STUNT = "WEB_STUNTPACK";
   var DLC_BIKER = "WEB_BIKERPACK";
   var DLC_SMUGGLER = "WEB_SMUGGLERPACK";
   var DLC_XMAS_2017 = "WEB_XMAS2017PACK";
   var DLC_ASSAULT = "WEB_ASSAULTPACK";
   var DLC_BATTLE = "WEB_BATTLEPACK";
   var DLC_ARENA = "WEB_ARENAPACK";
   var DLC_VINEWOOD = "WEB_VINEWOODPACK";
   var DLC_CASINOHEIST = "WEB_CASINOHEISTPACK";
   var DLC_SUMMER2020 = "WEB_SUM2020PACK";
   var DLC_HEIST4 = "WEB_HEIST4PACK";
   var DLC_TUNER = "WEB_TUNERPACK";
   var DLC_SECURITY = "WEB_SECURITYPACK";
   var DLC_SUM2 = "WEB_SUM2";
   var DLC_XMAS_2022 = "WEB_XMAS2022";
   var DLC_2023_01 = "WEB_2023_01";
   var DLC_2023_02 = "WEB_2023_02";
   var DLC_2024_01 = "WEB_2024_01";
   var DLC_2024_02 = "WEB_2024_02";
   var DLC_2025_1 = "WEB_2025_01";
   static var TXD_GEN9 = "SSSA_GEN9";
   static var DLC_GEN9 = "WEB_GEN9";
   var vehicles = {FUTO:{id:169,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:2,colourways:true,topSpeed:0.7243,acceleration:0.725,braking:0.1667,traction:0.6212},RUINER:{id:170,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_IMPONTE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:2,colourways:true,topSpeed:0.778,acceleration:0.7,braking:0.2667,traction:0.6667},ROMERO:{id:171,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_CHARIOT,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:2,colourways:true,topSpeed:0.6707,acceleration:0.375,braking:0.1667,traction:0.5909},PRAIRIE:{id:172,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BOLLOKAN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:2,colourways:true,topSpeed:0.7243,acceleration:0.55,braking:0.2,traction:0.5909},PATRIOT:{id:173,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAMMOTH,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.TXD_BATTLE,seats:4,colourways:true,topSpeed:0.6975,acceleration:0.5,braking:0.1067,traction:0.5152},SERRANO:{id:175,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BENEFAC,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:4,colourways:true,topSpeed:0.6975,acceleration:0.5,braking:0.1333,traction:0.6364},BJXL:{id:176,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:4,colourways:true,topSpeed:0.6975,acceleration:0.475,braking:0.2667,traction:0.6212},FQ2:{id:177,brand:com.rockstargames.gtav.web
   .WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_FATHOM,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:4,colourways:true,topSpeed:0.7243,acceleration:0.45,braking:0.0833,traction:0.6061},HABANERO:{id:178,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_EMPEROR,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:4,colourways:true,topSpeed:0.7351,acceleration:0.45,braking:0.0833,traction:0.6364},PBUS2:{id:179,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:11,colourways:false,livery:["PBUS2_SSA_1","PBUS2_SSA_2","PBUS2_SSA_3","PBUS2_SSA_4","PBUS2_SSA_5","PBUS2_SSA_6","PBUS2_SSA_7","PBUS2_SSA_8","PBUS2_SSA_9","PBUS2_SSA_10"],buyItNow:true,topSpeed:0.4829,acceleration:0.325,braking:0.0833,traction:0.3485},PATRIOT2:{id:180,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAMMOTH,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_BATTLE,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_BATTLE,seats:6,colourways:true,buyItNow:true,topSpeed:0.6975,acceleration:0.45,braking:0.1067,traction:0.4848},BLISTA3:{id:181,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_ARENA,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_ARENA,seats:2,colourways:false,topSpeed:0.7082,acceleration:0.575,braking:0.1833,traction:0.6364},VAMOS:{id:187,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_ARENA,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_ARENA,seats:2,colourways:true,topSpeed:0.778,acceleration:0.825,braking:0.1667,traction:0.6818},TULIP:{id:188,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_ARENA,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_ARENA,seats:4,colourways:true,topSpeed:0.7914,acceleration:0.8,braking:0.1667,traction:0.6818},RCBANDITO:{id:189,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_NONE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_ARENA,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_ARENA,seats:0,unlockable:true,colourways:false,topSpeed:0.4292,acceleration:0.35,braking:0.2667,traction:0.8939},GAUNTLET3:{id:190,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,buyItNow:true,topSpeed:0.7619,acceleration:0.7,braking:0.3,traction:0.7576},ISSI7:{id:191,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_WEENY,dlc:com.rockstargames.gtav
   .web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.7941,acceleration:0.7625,braking:0.3333,traction:1},ZION3:{id:192,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_UBERMACH,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.7995,acceleration:0.7625,braking:0.2833,traction:0.7121},NEBULA:{id:193,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VULCAR,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.7404,acceleration:0.6,braking:0.1667,traction:0.5909},HELLION:{id:194,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ANNIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.7163,acceleration:0.625,braking:0.1,traction:0.6061},IMPALER:{id:195,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_ARENA,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,buyItNow:true,topSpeed:0.8102,acceleration:0.775,braking:0.2,traction:0.7121},DYNASTY:{id:196,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_WEENY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:4,colourways:true,topSpeed:0.6331,acceleration:0.45,braking:0.1333,traction:0.5152},PEYOTE2:{id:197,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.7968,acceleration:0.8612,braking:0.3,traction:0.6848},GAUNTLET4:{id:198,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:2,colourways:true,topSpeed:0.8317,acceleration:0.9,braking:0.3,traction:0.7121},CARACARA2:{id:199,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_VINEWOOD,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_VINEWOOD,seats:4,colourways:true,topSpeed:0.7404,acceleration:0.675,braking:0.1,traction:0.6212},ASBO:{id:200,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAXWELL,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.6761,acceleration:0.585,braking:0.1567,traction:0.5818},KANJO:{id:201,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.7512,acceleration:0.8,braking:0.1667,traction:0.597},EVERON:{id:202,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:4,colourways:true,buyItNow:true,topSpeed:0.7297,acceleration:0.7375,braking:0.1,traction:0.6212},RETINUE2:{id:203,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.778,acceleration:0.6937,braking:0.24,traction:0.6212},YOSEMITE2:{id:204,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.7512,acceleration:0.9875,braking:0.2833,traction:0.7955},SUGOI:{id:205,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:4,colourways:true,buyItNow:true,topSpeed:0.837,acceleration:0.775,braking:0.2833,traction:1},SULTAN2:{id:206,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:4,colourways:true,buyItNow:true,topSpeed:0.7941,acceleration:0.825,braking:0.3333,traction:0.7576},OUTLAW:{id:207,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_NAGASAKI,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.6278,acceleration:1,braking:0.2,traction:0.6136},VAGRANT:{id:208,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAXWELL,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_CASINOHEIST,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_CASINOHEIST,seats:2,colourways:true,buyItNow:true,topSpeed:0.8029,acceleration:0.8313,braking:0.2083,traction:0.7121},DUKES3:{id:210,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_IMPONTE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUMMER2020,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUMMER2020,seats:2,colourways:true,buyItNow:true,topSpeed:0.7726,acceleration:0.7875,braking:0.25,traction:0.6667},CLUB:{id:216,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BF,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUMMER2020,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUMMER2020,seats:2,colourways:true,buyItNow:true,topSpeed:0.7512,acceleration:0.5938,braking:0.24,traction:0.6212},PENUMBRA2:{id:217,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAIBATSU,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUMMER2020,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUMMER2020,seats:2,colourways:true,buyItNow:true,topSpeed:0.7619,acceleration:0.75,braking:0.2667,traction:0.7121},SEMINOLE2:{id:221,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_CANIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUMMER2020,txd:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUMMER2020,seats:4,colourways:true,buyItNow:true,topSpeed:0.6975,acceleration:0.5,braking:0.2667,traction:0.6061},LANDSTLKR2:{id:222,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DUNDREARY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUMMER2020,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUMMER2020,seats:4,colourways:true,buyItNow:true,topSpeed:0.7243,acceleration:0.475,braking:0.2667,traction:0.6515},SLAMTRUCK:{id:223,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_HEIST4,seats:2,colourways:true,topSpeed:0.6707,acceleration:0.5625,braking:0.2,traction:0.5182},BRIOSO2:{id:224,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_GROTTI,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_HEIST4,seats:2,colourways:true,buyItNow:true,topSpeed:0.617,acceleration:0.4475,braking:0.0833,traction:0.5712},WEEVIL:{id:225,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BF,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_HEIST4,seats:2,colourways:true,buyItNow:true,topSpeed:0.7243,acceleration:0.47,braking:0.0867,traction:0.5394},VETO:{id:226,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_HEIST4,seats:1,colourways:true,topSpeed:0.4024,acceleration:1,braking:0.1167,traction:0.8636},VETO2:{id:227,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_HEIST4,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_HEIST4,seats:1,colourways:true,topSpeed:0.4292,acceleration:1,braking:0.1333,traction:0.8864},CALICO:{id:228,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.8035,acceleration:0.8462,braking:0.275,traction:1},REMUS:{id:229,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ANNIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.7877,acceleration:0.8175,braking:0.3,traction:1},DOMINATOR7:{id:230,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.8089,acceleration:0.855,braking:0.3067,traction:1},FUTO2:{id:231,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.7351,acceleration:0.7413,braking:0.175,traction:0.6348},RT3000:{id:232,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.7995,acceleration:0.78,braking:0.3333,traction:0.7818},WARRENER2:{id:233,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VULCAR,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.7834,acceleration:0.6625,braking:0.3167,traction:0.6545},SULTAN3:{id:234,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.786,acceleration:0.8462,braking:0.1733,traction:0.753},DOMINATOR8:{id:235,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.7796,acceleration:0.7568,braking:0.25,traction:0.7576},PREVION:{id:236,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web
   .WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_TUNER,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_TUNER,seats:2,colourways:true,buyItNow:true,topSpeed:0.8019,acceleration:0.7963,braking:0.2833,traction:0.7535},S95:{id:237,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.DLC_GEN9,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.TXD_GEN9,seats:2,colourways:true,buyItNow:false,isGen9:true,topSpeed:0.8129,acceleration:0.8275,braking:0.3667,traction:0.7606},ARBITERGT:{id:238,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_IMPONTE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.DLC_GEN9,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .TXD_GEN9,seats:2,colourways:true,buyItNow:false,isGen9:true,topSpeed:0.7968,acceleration:0.8287,braking:0.1733,traction:0.6918},BUFFALO4:{id:239,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SECURITY,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SECURITY,seats:4,colourways:true,buyItNow:true,topSpeed:0.8558,acceleration:0.8562,braking:0.3167,traction:0.7818},GRANGER2:{id:240,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SECURITY,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SECURITY,seats:8,colourways:true,buyItNow:true,topSpeed:0.7619,acceleration:0.5187,braking:0.28,traction:0.6606},IWAGEN:{id:241,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_OBEY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SECURITY,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SECURITY,seats:4,colourways:true,topSpeed:0.6868,acceleration:0.5787,braking:0.2583,traction:0.7167},PATRIOT3:{id:242,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAMMOTH,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SECURITY,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SECURITY,seats:4,colourways:true,buyItNow:true,topSpeed:0.6868,acceleration:0.575,braking:0.1617,traction:0.6015},RHINEHART:{id:243,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_UBERMACHT,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:4,colourways:true,topSpeed:0.8435,acceleration:0.8475,braking:0.295,traction:0.6924},POSTLUDE:{id:244,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:2,colourways:true,buyItNow:true,topSpeed:0.7029,acceleration:0.7375,braking:0.1333,traction:0.6015},KANJOSJ:{id:245,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.TXD_SUM2,seats:2,colourways:true,buyItNow:true,topSpeed:0.7565,acceleration:0.7875,braking:0.15,traction:0.6045},VIGERO2:{id:246,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:2,colourways:true,topSpeed:0.8475,acceleration:0.9112,braking:0.3167,traction:1},RUINER4:{id:247,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_IMPONTE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:2,colourways:true,topSpeed:0.8102,acceleration:0.7712,braking:0.2733,traction:0.7152},DRAUGUR:{id:248,brand:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:4,colourways:true,buyItNow:true,topSpeed:0.7898,acceleration:0.8562,braking:0.1613,traction:0.753},GREENWOOD:{id:249,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_SUM2,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_SUM2,seats:4,colourways:true,buyItNow:true,topSpeed:0.7673,acceleration:0.705,braking:0.2333,traction:0.697},TAHOMA:{id:250,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:2,colourways:true,topSpeed:0.8156,acceleration:0.745,braking:0.2083,traction:0.6994},TULIP2:{id:251,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:2,colourways:true,topSpeed:0.8156,acceleration:0.7882,braking:0.2267,traction:1},EVERON2:{id:252,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:2,colourways:true,buyItNow:true,topSpeed:0.8663,acceleration:0.8487,braking:0.2283,traction:1},EUDORA:{id:253,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_WILLARD,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:4,colourways:true,topSpeed:0.7404,acceleration:0.4875,braking:0.0883,traction:0.5727},ISSI8:{id:254,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_WEENY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:4,colourways:true,topSpeed:0.8019,acceleration:0.8038,braking:0.1827,traction:1},BOOR:{id:255,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:2,colourways:true,topSpeed:0.7995,acceleration:0.6675,braking:0.2267,traction:0.6258},JOURNEY2:{id:256,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ZIRCONIU,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:6,colourways:true,buyItNow:true,topSpeed:0.5366,acceleration:0.325,braking:0.0833,traction:0.4242},SURFER3:{id:257,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BF,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_XMAS_2022,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_XMAS_2022,seats:4,colourways:true,buyItNow:true,topSpeed:0.5366,acceleration:0.25,braking:0.1,traction:0.4697},L35:{id:258,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:2,colourways:true,buyItNow:false,topSpeed:0.7082,acceleration:0.59,braking:0.1067,traction:0.6176},BRIGHAM:{id:259,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ALBANY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:4,colourways:true,buyItNow:false,topSpeed:0.7297,acceleration:0.525,braking:0.1267,traction:0.5773},CLIQUE2:{id:260,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:2,colourways:true,buyItNow:false,topSpeed:0.6331,acceleration:0.495,braking:0.1167,traction:0.6303},RATEL:{id:261,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:2,colourways:true,buyItNow:true,topSpeed:0.7673,acceleration:0.855,braking:0.1067,traction:0.6642},MONSTROCITI:{id:262,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_MAIBATSU,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web
   .WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:2,colourways:true,buyItNow:false,topSpeed:0.7603,acceleration:0.6838,braking:0.123,traction:1},GAUNTLET6:{id:263,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_01,seats:2,colourways:true,topSpeed:0.863,acceleration:0.9169,braking:0.3117,traction:1},FR36:{id:264,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_FATHOM,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:2,colourways:true,topSpeed:0.8209,acceleration:0.7525,braking:0.2867,traction:0.7221},IMPALER5:{id:265,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.7726,acceleration:0.6344,braking:0.2883,traction:0.697},ASTEROPE2:{id:266,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.778,acceleration:0.595,braking:0.3,traction:0.7076},CAVALCADE3:{id:267,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ALBANY,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.6546,acceleration:0.6913,braking:0.2917,traction:0.6742},VIGERO3:{id:268,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:2,colourways:true,topSpeed:0.8475,acceleration:0.9112,braking:0.3167,traction:1},DOMINATOR9:{id:269,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:2,colourways:true,topSpeed:0.8692,acceleration:0.862,braking:0.31,traction:0.7712},DORADO:{id:271,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BRAVADO,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.7603,acceleration:0.5421,braking:0.1667,traction:0.5591},IMPALER6:{id:272,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.778,acceleration:0.75,braking:0.2333,traction:0.647},TERMINUS:{id:273,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_CANIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.7941,acceleration:0.6725,braking:0.1833,traction:0.6629},VIVANITE:{id:274,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2023_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2023_02,seats:4,colourways:true,topSpeed:0.837,acceleration:0.2737,braking:0.26,traction:0.6602},VORSCHLAG:{id:275,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_BENEFAC,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_01,seats:4,colourways:true,topSpeed:0.8424,acceleration:0.6625,braking:0.2083,traction:0.6258},CASTIGATOR:{id:276,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_CANIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_01,seats:4,colourways:true,topSpeed:0.8531,acceleration:0.7263,braking:0.2533,traction:0.6861},YOSEMITE4:{id:277,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_01,seats:2,colourways:true,topSpeed:0.7163,acceleration:0.5838,braking:0.1767,traction:0.6061},DOMINATOR10:{id:278,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_01,seats:2,colourways:true,topSpeed:0.8209,acceleration:0.75,braking:0.23,traction:0.7221},PIZZABOY:{id:279,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_PEGASSI,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_01,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_01,seats:1,buyItNow:true,colourways:false,topSpeed:0.4963,acceleration:0.3,braking:0.11,traction:0.503},CHAVOSV6:{id:280,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DINKA,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_02,seats:4,buyItNow:false,colourways:true,topSpeed:0.7834,acceleration:0.685,braking:0.23,traction:0.7739},URANUS:{id:281,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_02,seats:2,buyItNow:false,colourways:true,topSpeed:0.8317,acceleration:0.8112,braking:0.16,traction:0.7697},FIREBOLT:{id:282,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_VAPID,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2024_02,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2024_02,seats:2,buyItNow:false,colourways:true,topSpeed:0.7753,acceleration:0.7405,braking:0.13,traction:0.7091},DRIFTL352:{id:283,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames
   .gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2025_1,seats:2,buyItNow:false,colourways:true,topSpeed:0.7136,acceleration:1,braking:0.1067,traction:0.1762},HARDY:{id:284,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ANNIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2025_1,seats:4,buyItNow:false,colourways:true,topSpeed:0.8456,acceleration:0.678,braking:0.1887,traction:0.6136},MINIMUS:{id:285,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_ANNIS,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER
   .prototype.TXD_2025_1,seats:4,buyItNow:false,colourways:true,topSpeed:0.7968,acceleration:0.7037,braking:0.1833,traction:0.7727},L352:{id:286,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2025_1,seats:2,buyItNow:false,colourways:true,topSpeed:0.7458,acceleration:0.59,braking:0.1067,traction:0.6364},WOODLANDER:{id:287,brand:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_KARIN,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2025_1,seats:4,buyItNow:false,colourways:true,topSpeed:0.8612,acceleration:0.65,braking:0.1617,traction:0.6671},TAMPA4:{id:288,brand:com
   .rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.BRAND_DECLASSE,dlc:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.DLC_2025_1,txd:com.rockstargames.gtav.web.WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER.prototype.TXD_2025_1,seats:2,buyItNow:false,colourways:true,topSpeed:0.8585,acceleration:0.925,braking:0.1,traction:0.5515}};
   function WWW_SOUTHERNSANANDREASSUPERAUTOS_COM_WRAPPER_WRAPPER()
   {
      super();
   }
}
